FROM node:20.9

ARG user=appuser
ARG group=appuser
ARG uid=1001
ARG gid=1001
RUN groupadd -g ${gid} ${group}
RUN useradd -u ${uid} -g ${group} -s /bin/sh -m ${user}

COPY website /website

WORKDIR /website

ENV SECRET_KEY=d8141cxkMIaNn5mvvl2A+VYAm40SHYaurBV7riC0FEU=
ENV NODE_ENV=production

RUN npm install

RUN npm install iron-session

RUN npm run build

RUN chown -R ${user} .

RUN chsh -s /usr/sbin/nologin root 

USER ${uid}:${gid}

CMD [ "npm", "run", "start" ]